### ISSUE TITLE
lcurse doesn't seem to be working for me..

### ISSUE THREAD

**Issue by steorra** [ephraim/lcurse#5]
..I'm running xubuntu 14.10 with crossover installed so therefore my addons are located under my homedir /.cxoffice/WorldofWarcraft/drive c/Program Files/World of Warcraft end that path is reflect as such under lcurse preference as my install directory.  I've copied over a few days old worth of addons in the AddOns directory and attempted to click on Update Catalog.. I'm not seeing any addons listed at all.  If I click on update all addons, it just hangs terminally searching.. Help?

steorra

**Comment by ephraim** [comment]
Hey Steorra,

"Update Catalog" will update an internal file which represents the available addons on curse.com. This has nothing to do with your installed addons!

Please use "General -> Import Addons" to import the already installed addons
or
Use "Addons -> Add Addon" to add addons to your Wow installation via lcurse (because you already updated the catalog, you only need to type the name of the addon in the Add-AddonDialog and you will get a dropdown of addons, the typed part is part of the name)

Hope this helped!

cheers
Ephraim

**Comment by steorra** [comment]
I feel like an idiot..that did the trick for me..thanks..:)


steorra
